version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: npm
    directory: "/apps/website"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(website)"
    groups:
      react:
        patterns: ["react", "react-dom", "@types/react", "@types/react-dom", "next"]
      tailwind:
        patterns: ["tailwindcss", "@tailwindcss/*"]
